from ragger.config import (
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_MODEL_NAME,
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_PERSIST_DIRECTORY,
    DEFAULT_WORKSPACE,
)

__all__ = [
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_MODEL_NAME",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_PERSIST_DIRECTORY",
    "DEFAULT_WORKSPACE",
]
